changelog-type: ''
hash: c86b528cf733f23aeea45be476b5f3ab3c27b9d6064f422f5c162c9a824bd76c
synopsis: Basic libraries
changelog: ''
all-versions:
- '3.0.3.1'
- '3.0.3.2'
- '4.0.0.0'
- '4.1.0.0'
- '4.2.0.0'
- '4.2.0.1'
- '4.2.0.2'
- '4.3.0.0'
- '4.3.1.0'
- '4.4.0.0'
- '4.4.1.0'
- '4.5.0.0'
- '4.5.1.0'
- '4.6.0.0'
- '4.6.0.1'
- '4.7.0.0'
- '4.7.0.1'
- '4.7.0.2'
- '4.8.0.0'
latest: '4.8.0.0'
description-type: haddock
description: ! 'This package contains the "Prelude" and its support libraries,

  and a large collection of useful libraries ranging from data

  structures to parsing combinators and debugging utilities.'
