changelog-type: ''
hash: 6af099d484ca11273e7e878b131973cf7fd00d2ef049865c7328c8a393044835
synopsis: Create pkg-config configuration files
changelog: ''
all-versions:
- '0.1.0.0'
- '0.2.0.0'
- '0.2.1.0'
latest: '0.2.1.0'
description-type: haddock
description: ! 'Create /pkg-config/ configuration file from Haskell code using combinators

  specialized for this purpose.


  One of the possible usage examples of this library is generating @.pc@ files

  from <http://shakebuild.com Shake build system>.


  For usage example see "Data.PkgConfig" module.'
