changelog-type: ''
hash: e6a798ab88123139457555acc942036d31823e9efaf413334c16866b86bfeb92
synopsis: By using this package, you can make application configurable.
changelog: ''
all-versions:
- '0.1'
- '0.1.0.2'
latest: '0.1.0.2'
description-type: haddock
description: ! 'I inspired by xmonad. Xmonad is configurable by using user''s own
  main.

  This package make your application configurable like xmonad.'
