changelog-type: ''
hash: 9ff923feefc20ee13547d50cc5d961ece9ac071369b15ed2c7b55b304dd5aa73
synopsis: Simple text configuration file parser library.
changelog: ''
all-versions:
- '0.2'
- '0.5'
- '0.5.1'
- '0.5.2'
latest: '0.5.2'
description-type: haddock
description: ! 'This Library can be used to keep track of simple information

  in simple games and other programs.'
