homepage: ''
changelog-type: ''
hash: 302eead00feecf4d4327e233d9d118ce314dff2e34cbbd131d774378a54630d8
test-bench-deps:
  unix: ! '>=2.5.1.1'
  base: -any
  hspec: ! '>=1.4'
  monad-logger: ! '>=0.3.4.0'
  logging: -any
maintainer: johnw@newartisans.com
synopsis: Simplified logging in IO for application writers.
changelog: ''
basic-deps:
  pcre-light: ! '>=0.4'
  bytestring: ! '>=0.9.2.1'
  base: ! '>=3 && <5'
  time: ! '>=1.4'
  text: ! '>=0.11.3.1'
  monad-control: ! '>=0.3.2.3'
  lifted-base: ! '>=0.2.2.0'
  fast-logger: ! '>=2.1.5'
  binary: ! '>=0.5.1.1'
  old-locale: ! '>=1.0.0.5'
  monad-logger: ! '>=0.3.4.0'
  transformers: ! '>=0.3.0.0'
all-versions:
- '1.0.0'
- '1.1.0'
- '1.2.0'
- '1.3.0'
- '1.4.0'
- '1.4.1'
- '2.1.0'
- '2.2.0'
author: John Wiegley
latest: '2.2.0'
description-type: haddock
description: ! '@logging@ is a wrapper around @monad-logger@ and @fast-logger@ which
  makes

  it easy to log from any ''MonadLogger'' environment, or from ''IO''.  It

  provides the following conveniences on top of those libraries:


  - A ''MonadLogger'' instance for ''IO''.  Usually this is bad for libraries, but

  can be very convenient for application writers who know they always want

  to log from IO to the console.  If you need to log to other sources, or to

  make logging compile-time optional, use @monad-logger@ directly.


  - A set of shorter functions to type: ''debug'', ''log'', ''warn'', plus others

  that flush after each message, or which allow providing a message source

  string.


  - Logging variants of ''error'', ''trace'' and ''traceShow'', called ''errorL'',

  ''traceL'' and ''traceShowL''.  These use ''unsafePerformIO'' in order to act as

  direct replacements, so the usual caveats apply.


  - A global function, ''setDebugLevel'', which uses a global ''IORef'' to record

  the logging level, saving you from having to carry around the notion of

  "verbosity level" in a Reader environment.


  - A set of "timed" variants, ''timedLog'' and ''timedDebug'', which report how

  long the specified action took to execute in wall-clock time.'
license-name: MIT
