changelog-type: ''
hash: 1a522cabfb4e24618b545b543d8e31a6c621cdb33cd655bb35eff7be7e528dc0
synopsis: ExtremlyEasyConfig - Extremly Simple parser for config files
changelog: ''
all-versions:
- '1.0'
latest: '1.0'
description-type: haddock
description: ! 'Implementation of a very simple parser for parameters recognition.

  It recognizes given parameters and their values.

  As input it becomes list of parameters and all their possible values in format [ParameterInput]

  and input String where parameters will be searched for.

  As output it deliveres recognized parameters and their values in format [ParameterOutput],

  where only these parameters are present which have been found in the input string.

  In output list each exisitng parameter has exactly one value - this one that has

  been recognized in the input string.

  Parameters in the input string have to be always given in following format:

  (\<flagname> \<parameter>)*.

  Anything what is not recognized as parameter or value is ignored.'
