changelog-type: ''
hash: 8241dba8379b6490326c4d8cf00a2b3b49a5865ad2cb6fe05c865698e51c9c2d
synopsis: Configuration management
changelog: ''
all-versions:
- '0.0.1'
- '0.1.0'
- '0.2.0'
- '0.2.1'
- '0.2.2'
latest: '0.2.2'
description-type: haddock
description: Configuration management
