homepage: ''
changelog-type: ''
hash: b379ef0ff5547b98554c3aa98588c4a4cfb246c213cc4715f5db713f4919d922
test-bench-deps:
  base: ! '>=4.5.0 && <5.0.0'
  unordered-containers: ! '>=0.2.0'
  text: ! '>=0.11.0'
  tasty-quickcheck: ! '>=0.8.0'
  hashable: ! '>=1.2.0'
  failure: ! '>=0.2.0'
  tasty: ! '>=0.10.0'
  deepseq: ! '>=1.3'
  QuickCheck: ! '>=2.6.0'
  yaml: ! '>=0.8.10'
maintainer: mitroshin@selectel.org
synopsis: Configuration management
changelog: ''
basic-deps:
  base: ! '>=4.5.0 && <5.0.0'
  unordered-containers: ! '>=0.2.0'
  text: ! '>=0.11.0'
  failure: ! '>=0.2.0'
  deepseq: ! '>=1.3'
  yaml: ! '>=0.8.10'
all-versions:
- '0.0.1'
- '0.1.0'
- '0.2.0'
- '0.2.1'
- '0.2.2'
- '0.2.3'
- '0.3.0'
author: ! 'Fedor Gogolev <knsd@knsd.net>

  Mitroshin Maxim <mitroshin@selectel.org>

  Simon Hengel <sol@typeful.net>'
latest: '0.3.0'
description-type: haddock
description: Configuration management
license-name: MIT
