changelog-type: ''
hash: 7094680a8c3b84cd69a82231dffa4bb9e8e93506446fd49f76f6d7fa5e2cdbb6
test-bench-deps:
  base: ==4.7.* || ==4.6.* || ==4.5.*
  unordered-containers: ==0.2.*
  text: ==1.1.* || ==1.0.* || ==0.11.*
  tasty-quickcheck: ==0.8.*
  hashable: ==1.2.*
  failure: ==0.2.*
  tasty: ==0.8.*
  deepseq: ==1.3.*
  QuickCheck: ==2.6.*
  yaml: ==0.8.*
synopsis: Configuration management
changelog: ''
basic-deps:
  base: ==4.7.* || ==4.6.* || ==4.5.*
  unordered-containers: ==0.2.*
  text: ==1.1.* || ==1.0.* || ==0.11.*
  failure: ==0.2.*
  deepseq: ==1.3.*
  yaml: ==0.8.*
all-versions:
- '0.0.1'
- '0.1.0'
- '0.2.0'
- '0.2.1'
- '0.2.2'
latest: '0.2.2'
description-type: haddock
description: Configuration management
