homepage: ''
changelog-type: ''
hash: 6e842cf6a896ed9d2fdf3140423665a6a01ff95256929cf5601d0d9125db2ad9
test-bench-deps: {}
maintainer: llvm@henning-thielemann.de
synopsis: Generate Pkg-Config configuration file for LLVM
changelog: ''
basic-deps:
  explicit-exception: ! '>=0.1.7 && <0.2'
  Cabal: ! '>=1.14 && <1.20'
  base: ! '>=4.2 && <5'
  process: ! '>=1.0 && <1.3'
  utility-ht: ! '>=0.0.8 && <0.1'
  transformers: ! '>=0.2.2 && <0.4'
all-versions:
- '0.0'
author: Henning Thielemann
latest: '0.0'
description-type: haddock
description: ! 'Building the @llvm-base@ package is fragile due to its configuration
  process.

  It would be much simpler, if LLVM would support pkg-config

  since this is nicely integrated in Cabal.

  However, LLVM developers do not seem to care much about it:

  <http://llvm.org/bugs/show_bug.cgi?id=9405>.

  If we are lucky we get pkg-config support in Debian Linux.

  Until this comes true, you can use this program.

  It calls @llvm-config@ and writes its output to a PC file.


  > llvm-pkg-config


  calls default @llvm-config@ and writes the generated file to standard output.


  > sudo llvm-pkg-config --install


  installs the PC file at a default location.

  This should be the standard task to perform.


  > llvm-pkg-config --llvm-config=/custom/path/to/llvm-config


  if you have multiple versions of LLVM installed

  you may choose an @llvm-config@ other than the default one.'
license-name: BSD3
