homepage: ''
changelog-type: ''
hash: 47afbbcc1d69c728ebc995c846389e9dcf86dce0832eb22f5c5b25fb89ed39a6
test-bench-deps: {}
maintainer: edsko@well-typed.com
synopsis: Hackage security library
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.2 && <0.11'
  Cabal: ! '>=1.12 && <1.25'
  base: ! '>=4.8 && <5'
  time: ! '>=1.2 && <1.6'
  base64-bytestring: ! '>=1.0 && <1.1'
  ed25519: ! '>=0.0 && <0.1'
  filepath: ! '>=1.2 && <1.5'
  network: ! '>=2.6 && <2.7'
  parsec: ! '>=3.1 && <3.2'
  containers: ! '>=0.4 && <0.6'
  tar: ! '>=0.4.2 && <0.5'
  ghc-prim: -any
  zlib: ! '>=0.5 && <0.7'
  network-uri: ! '>=2.6 && <2.7'
  mtl: ! '>=2.2 && <2.3'
  transformers: ! '>=0.4 && <0.5'
  template-haskell: -any
  directory: ! '>=1.1 && <1.3'
  cryptohash: ! '>=0.11 && <0.12'
all-versions:
- '0.1.0.0'
- '0.2.0.0'
author: Edsko de Vries
latest: '0.2.0.0'
description-type: haddock
description: ! 'The hackage security library provides both server and

  client utilities for securing the Hackage package server

  (<http://hackage.haskell.org/>).  It is based on The Update

  Framework (<http://theupdateframework.com/>), a set of

  recommendations developed by security researchers at

  various universities in the US as well as developers on the

  Tor project (<https://www.torproject.org/>).


  The current implementation supports only index signing,

  thereby enabling untrusted mirrors. It does not yet provide

  facilities for author package signing.


  The library has two main entry points:

  "Hackage.Security.Client" is the main entry point for

  clients (the typical example being @cabal@), and

  "Hackage.Security.Server" is the main entry point for

  servers (the typical example being @hackage-server@).


  This is a beta release.'
license-name: BSD3
