before_install:
- openssl aes-256-cbc -K $encrypted_a93853a94b97_key -iv $encrypted_a93853a94b97_iv
  -in id_rsa.enc -out id_rsa -d
- mkdir -p ~/.ssh
- mv id_rsa ~/.ssh
- chmod 400 ~/.ssh/id_rsa
- git config --global user.email "michael+all-cabal-metadata@snoyman.com"
- git config --global user.name "Commercial Haskell all-cabal-metadata Travis job"
script:
- "./update.sh"
