changelog-type: ''
hash: 530cc64fb69fcb728155f810189dd182e6b26235bbcd4d899e1662992d3945ba
synopsis: Amazon Config SDK.
changelog: ''
all-versions:
- '0.0.0'
- '0.0.1'
- '0.0.2'
- '0.0.3'
- '0.0.4'
- '0.0.5'
- '0.0.6'
- '0.0.7'
- '0.0.8'
- '0.1.0'
- '0.1.1'
- '0.1.2'
- '0.1.3'
- '0.1.4'
- '0.2.0'
- '0.2.1'
- '0.2.2'
- '0.2.3'
- '0.3.0'
- '0.3.1'
- '0.3.2'
- '0.3.3'
- '0.3.4'
latest: '0.3.4'
description-type: haddock
description: ! 'Amazon Config is a fully managed service that provides you with an
  Amazon

  resource inventory, configuration history, and configuration change

  notifications to enable security and governance. With Amazon Config you can

  discover existing Amazon resources, export a complete inventory of your

  Amazon resources with all configuration details, and determine how a resource

  was configured at any point in time. These capabilities enable compliance

  auditing, security analysis, resource change tracking, and troubleshooting.


  /See:/ <http://docs.aws.amazon.com/config/latest/APIReference/Welcome.html AWS API
  Reference>


  /Warning:/ This is an experimental preview release which is still under

  heavy development and not intended for public consumption, caveat emptor!'
