changelog-type: ''
hash: ec9b7c5acc34d6aec3a96caf94993486e52ac1e4ee057fbfea148979972670c8
test-bench-deps: {}
synopsis: Amazon Config SDK.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  amazonka-core: ==0.3.4.*
all-versions:
- '0.0.0'
- '0.0.1'
- '0.0.2'
- '0.0.3'
- '0.0.4'
- '0.0.5'
- '0.0.6'
- '0.0.7'
- '0.0.8'
- '0.1.0'
- '0.1.1'
- '0.1.2'
- '0.1.3'
- '0.1.4'
- '0.2.0'
- '0.2.1'
- '0.2.2'
- '0.2.3'
- '0.3.0'
- '0.3.1'
- '0.3.2'
- '0.3.3'
- '0.3.4'
latest: '0.3.4'
description-type: markdown
description: ! '# Amazon Config SDK


  > _Warning:_ This is an experimental preview release which is still under heavy
  development and not intended for public consumption, _caveat emptor_!


  * [Description](#description)

  * [Contribute](#contribute)

  * [Licence](#licence)


  ## Description


  Amazon Config is a fully managed service that provides you with an Amazon

  resource inventory, configuration history, and configuration change

  notifications to enable security and governance. With Amazon Config you can

  discover existing Amazon resources, export a complete inventory of your

  Amazon resources with all configuration details, and determine how a resource

  was configured at any point in time. These capabilities enable compliance

  auditing, security analysis, resource change tracking, and troubleshooting.


  Documentation is available via [Hackage](http://hackage.haskell.org/package/amazonka-config)

  and the [AWS API Reference](http://docs.aws.amazon.com/config/latest/APIReference/Welcome.html).



  ## Contribute


  For any problems, comments, or feedback please create an issue [here on GitHub](https://github.com/brendanhay/amazonka/issues).


  > _Note:_ this library is an auto-generated Haskell package. Please see `amazonka-gen`
  for more information.



  ## Licence


  `amazonka-config` is released under the [Mozilla Public License Version 2.0](http://www.mozilla.org/MPL/).


  Parts of the code are derived from AWS service descriptions, licensed under Apache
  2.0.

  Source files subject to this contain an additional licensing clause in their header.

'
