homepage: https://github.com/brendanhay/amazonka
changelog-type: ''
hash: d8a2c5c2618e64d48b8ee62eaa7445636c012b23c4d65f5b6ed144b80b77246f
test-bench-deps:
  amazonka-application-autoscaling: ==1.4.3.*
  bytestring: -any
  base: -any
  time: -any
  unordered-containers: -any
  text: -any
  amazonka-test: ==1.4.3.*
  amazonka-core: ==1.4.3.*
  tasty-hunit: -any
  tasty: -any
maintainer: Brendan Hay <brendan.g.hay@gmail.com>
synopsis: Amazon Application Auto Scaling SDK.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  amazonka-core: ==1.4.3.*
all-versions:
- '1.4.2'
- '1.4.3'
author: Brendan Hay
latest: '1.4.3'
description-type: markdown
description: ! '# Amazon Application Auto Scaling SDK


  * [Version](#version)

  * [Description](#description)

  * [Contribute](#contribute)

  * [Licence](#licence)



  ## Version


  `1.4.3`



  ## Description


  Application Auto Scaling is a general purpose Auto Scaling service for supported
  elastic AWS resources. With Application Auto Scaling, you can automatically scale
  your AWS resources, with an experience similar to that of Auto Scaling.


  At this time, Application Auto Scaling only supports scaling Amazon ECS services.


  For example, you can use Application Auto Scaling to accomplish the following tasks:


  -   Define scaling policies for automatically adjusting your application’s resources


  -   Scale your resources in response to CloudWatch alarms


  -   View history of your scaling events


  Documentation is available via [Hackage](http://hackage.haskell.org/package/amazonka-application-autoscaling)

  and the [AWS API Reference](https://aws.amazon.com/documentation/).


  The types from this library are intended to be used with [amazonka](http://hackage.haskell.org/package/amazonka),

  which provides mechanisms for specifying AuthN/AuthZ information and sending requests.


  Use of lenses is required for constructing and manipulating types.

  This is due to the amount of nesting of AWS types and transparency regarding

  de/serialisation into more palatable Haskell values.

  The provided lenses should be compatible with any of the major lens libraries

  [lens](http://hackage.haskell.org/package/lens) or [lens-family-core](http://hackage.haskell.org/package/lens-family-core).


  ## Contribute


  For any problems, comments, or feedback please create an issue [here on GitHub](https://github.com/brendanhay/amazonka/issues).


  > _Note:_ this library is an auto-generated Haskell package. Please see `amazonka-gen`
  for more information.



  ## Licence


  `amazonka-application-autoscaling` is released under the [Mozilla Public License
  Version 2.0](http://www.mozilla.org/MPL/).


  Parts of the code are derived from AWS service descriptions, licensed under Apache
  2.0.

  Source files subject to this contain an additional licensing clause in their header.

'
license-name: OtherLicense
