changelog-type: ''
hash: 9ce20e6a81daead7b06166aff0ceb787f55aa513a695bf7188ea01131e91aeda
synopsis: Haskell bindings to a security-related functions of the Windows API
changelog: ''
all-versions:
- '0.1'
- '0.1.1'
latest: '0.1.1'
description-type: haddock
description: ! 'This package contains bindings for security-related functions of the
  Windows API.

  Its main features are account name/SID lookup and editing securable objects access
  control lists.'
