changelog-type: ''
hash: fbf1dee8a66013e6a03f73f656f875ed1f49f4dea2f825af53ea1b302ff34865
synopsis: A pattern for configuring programs.
changelog: ''
all-versions:
- '0.1.0.1'
latest: '0.1.0.1'
description-type: haddock
description: ! 'Turns out, all of our executables shared the same sort of

  pattern: Parse the command line to locate a config file,

  read and parse the config file, set up `hslogger` based on

  some stuff found in the config file, and pass the rest of

  the config to the actual program. This library makes doing

  that pattern super easy. It is meant to be a rather

  particular (as opposed to general) solution for this sort

  of problem.'
