homepage: ''
changelog-type: ''
hash: 33dcb5f7f58c182aa4fd2f29742e20d5f2cb4e99da7b366a8e352024829543c8
test-bench-deps: {}
maintainer: rick@owenssoftware.com
synopsis: A pattern for configuring programs.
changelog: ''
basic-deps:
  unix: -any
  base: ! '>=4 && <5'
  text: -any
  filepath: -any
  hslogger: -any
  aeson: -any
  yaml: -any
  directory: -any
all-versions:
- '0.1.0.1'
author: Rick Owens
latest: '0.1.0.1'
description-type: haddock
description: ! 'Turns out, all of our executables shared the same sort of

  pattern: Parse the command line to locate a config file,

  read and parse the config file, set up `hslogger` based on

  some stuff found in the config file, and pass the rest of

  the config to the actual program. This library makes doing

  that pattern super easy. It is meant to be a rather

  particular (as opposed to general) solution for this sort

  of problem.'
license-name: Apache-2.0
