changelog-type: ''
hash: 18fe04847f9bb8bdaeeea627d80e581aaaea53d607f5ba88def7d2acbd686ebb
synopsis: Configuration management
changelog: ''
all-versions:
- '0.0.0.1'
- '0.0.1.1'
- '0.1.0.0'
- '0.2.0.0'
- '0.2.0.1'
- '0.2.0.2'
- '0.3.0.0'
latest: '0.3.0.0'
description-type: haddock
description: ! 'A configuration management library for programs and daemons.


  Features include:


  * Automatic, dynamic reloading in response to modifications to

  configuration files.


  * A simple, but flexible, configuration language, supporting several

  of the most commonly needed types of data, along with

  interpolation of strings from the configuration or the system

  environment (e.g. @$(HOME)@).


  * Subscription-based notification of changes to configuration

  properties.


  * An @import@ directive allows the configuration of a complex

  application to be split across several smaller files, or common

  configuration data to be shared across several applications.


  For details of the configuration file format, see

  <http://hackage.haskell.org/packages/archive/configurator/latest/doc/html/Data-Configurator.html>.'
