changelog-type: ''
hash: 460275c2b723788338606e7a7a23d569877374f73fed4e549c30150b58da3759
synopsis: A small program for swapping out dot files.
changelog: ''
all-versions:
- '0.0.0'
- '0.0.1'
latest: '0.0.1'
description-type: haddock
description: Manage multiple configuration profiles for the same program.  Swap out
  dot files quickly.
