changelog-type: ''
hash: 456ade695f5c5ff59f75e1e6ab939b7c80eb447d99028c5e7ad60d910759b6ca
synopsis: Template haskell for reading ConfigFiles.
changelog: ''
all-versions:
- '0.1'
- '0.2'
latest: '0.2'
description-type: haddock
description: ! 'This module provides syntax for concise definitions of config files
  from

  Data.ConfigFile through template haskell.

  For example, the following splice,

  $(genConf "Example" [$conf|

  elbow/center -> ec :: Double

  elbow/min    -> emi :: Double

  elbow/max    -> ema :: Double

  |])

  resolves into declaration of the following datatype

  data Example = Example

  ec  :: Double

  ,emi :: Double

  ,ema :: Double

  and a function

  loadExample :: (MonadIO m) => FilePath -> m (Either CPError Example) ,

  which uses Data.ConfigFile to read a values for the above struct from

  a file.'
