homepage: https://gitlab.com/guyonvarch/config-manager
changelog-type: ''
hash: cfcda5c4ee32c9b5655b7ecd71ae40fa0b366192a820b47622d5cd62cffc1057
test-bench-deps:
  test-framework-hunit: -any
  test-framework: -any
  base: -any
  unordered-containers: -any
  text: -any
  HUnit: -any
  config-manager: -any
  temporary: -any
  directory: -any
maintainer: joris@guyonvarch.me
synopsis: Configuration management
changelog: ''
basic-deps:
  base: <5
  unordered-containers: -any
  text: -any
  filepath: -any
  parsec: -any
all-versions:
- '0.0.0.1'
- '0.0.0.2'
author: Joris Guyonvarch
latest: '0.0.0.2'
description-type: haddock
description: ! 'A configuration management library which supports:


  * name-value bindings,


  * required or optional imports,


  * comments.'
license-name: GPL-3
