homepage: https://gitlab.com/guyonvarch/config-manager
changelog-type: ''
hash: 3b3f9e4e2af9381da4cc58923e27d87cd7d4b19f65c40f8684a82c00bee6a3f6
test-bench-deps:
  test-framework-hunit: -any
  test-framework: -any
  base: -any
  unordered-containers: -any
  text: -any
  HUnit: -any
  config-manager: -any
  temporary: -any
  directory: -any
maintainer: joris@guyonvarch.me
synopsis: Configuration management
changelog: ''
basic-deps:
  base: <5
  unordered-containers: -any
  text: -any
  filepath: -any
  parsec: -any
all-versions:
- '0.0.0.1'
- '0.0.0.2'
- '0.1.0.0'
author: Joris Guyonvarch
latest: '0.1.0.0'
description-type: haddock
description: ! 'A configuration management library which supports:


  * name-value bindings,


  * required or optional imports,


  * comments.'
license-name: GPL-3
