changelog-type: ''
hash: 3b910e620d5feacc20f56048d235b6e0bfad56d13f60ad31cc374b5d15e1deb4
synopsis: Parse config files
changelog: ''
all-versions:
- '0.1'
latest: '0.1'
description-type: haddock
description: Parses a config file into [(String, [(String, String)])]
