changelog-type: ''
hash: 84834a19c8ce4ee14d29c6312fd628103b318333019b3c8dfcd7d4978e402328
synopsis: Declare types as Configurable then specialize them all in one place
changelog: ''
all-versions:
- '0.1.0.0'
latest: '0.1.0.0'
description-type: haddock
description: Declare types as Configurable then specialize them all in one place
