changelog-type: ''
hash: 84c6e853d6f5b454ce6a8c2a31f9172c82d7479efdd5a7bc1bcd53bc5859477a
synopsis: Simple, layout-based value language similar to YAML or JSON
changelog: ''
all-versions:
- '0.1'
- '0.1.1'
- '0.2'
- '0.3'
- '0.4'
- '0.4.0.1'
latest: '0.4.0.1'
description-type: haddock
description: ! 'This package implments a language similar to YAML or JSON but

  with fewer special cases and fewer dependencies. It emphasizes

  layout structure for sections and lists, and requires quotes

  around strings.'
