changelog-type: ''
hash: 72c7a0c39daa90cff5af1dacf513a6287470f8eb14b0a38e7798fc9ca55cd351
synopsis: Tools for specifying and parsing configurations
changelog: ''
all-versions:
- '0.2.1'
- '0.2.2'
- '0.2.3'
- '0.2.4'
- '0.2.4.1'
- '0.2.5'
- '0.2.6'
- '0.2.7'
- '0.2.8'
- '0.2.9'
- '0.2.10'
- '0.2.11'
- '0.2.12'
latest: '0.2.12'
description-type: haddock
description: ! 'Tools for specifying and parsing configurations


  This package provides a collection of utils on top of the packages

  <http://hackage.haskell.org/package/optparse-applicative optparse-applicative>,

  <http://hackage.haskell.org/package/aeson aeson>, and

  <http://hackage.haskell.org/package/yaml yaml> for configuring libraries and

  applications in a convenient and composable way.


  The main features are


  1. configuration management through integration of command line option

  parsing and configuration files and


  2. a @Setup.hs@ file that generates a @PkgInfo@ module for each component

  of a package that provides information about the package and the build.


  Documentation on how to use this package can be found in the

  <https://github.com/alephcloud/hs-configuration-tools/blob/master/README.md README>

  and in the API documentation of the modules "Configuration.Utils" and

  "Configuration.Utils.Setup".'
