homepage: https://github.com/aisamanra/config-ini
changelog-type: markdown
hash: 8ad5c88a3e00e09e40d8efda49a11f442903f2b2dca73fb383a1507e64bc418a
test-bench-deps:
  base: -any
  unordered-containers: -any
  text: -any
  doctest: -any
  ini: -any
  config-ini: -any
  QuickCheck: -any
  microlens: -any
  directory: -any
maintainer: Getty Ritter <gettyritter@gmail.com>
synopsis: A library for simple INI-based configuration files.
changelog: ! '0.1.2.1

  =======


  - GHC 8.2 compatibility


  0.1.2.0

  =======


  - GHC 7.8 backwards-compatibility

  - Started changelog

'
basic-deps:
  base: ! '>=4.7 && <5'
  unordered-containers: ! '>=0.2.7 && <0.3'
  text: ! '>=1.2.2 && <1.3'
  megaparsec: ! '>=5.1.2 && <5.2'
  config-ini: -any
  transformers: ! '>=0.4.1 && <0.6'
all-versions:
- '0.1.0.0'
- '0.1.1.0'
- '0.1.2.0'
- '0.1.2.1'
author: Getty Ritter <gettyritter@gmail.com>
latest: '0.1.2.1'
description-type: haddock
description: ! 'The @config-ini@ library is a small monadic language

  for writing simple configuration languages with convenient,

  human-readable error messages.


  > parseConfig :: IniParser (Text, Int, Bool)

  > parseConfig = section "NETWORK" $ do

  >   user <- field        "user"

  >   port <- fieldOf      "port" number

  >   enc  <- fieldFlagDef "encryption" True

  >   return (user, port, enc)'
license-name: BSD3
