changelog-type: ''
hash: 0bf5a0763fc229193ff45a71b3f322e70f3e5a24aaed6783e48cbd192d654157
synopsis: parser for config files, shell variables, command line args.
changelog: ''
all-versions:
- '0.0.2'
- '0.0.3'
latest: '0.0.3'
description-type: haddock
description: ! 'WARNING NOT READY FOR USE YET.  JUST PUTTING IT OUT THERE TO HAVE
  A DISCUSSION.


  Read runtime configuration from files, command line, and shell

  environment in a uniform, canonical, and flexible way.  Inspired

  by, among others, Configurator, cmdargs, optparse-applicative.'
