homepage: https://github.com/aisamanra/config-ini
changelog-type: ''
hash: 0a59447d3fd2c387efb8da7a930e95a111c07d539ad4302dd6a4963a7cb0ec84
test-bench-deps:
  base: -any
  unordered-containers: -any
  text: -any
  ini: -any
  config-ini: -any
  QuickCheck: -any
  directory: -any
maintainer: Getty Ritter <gettyritter@gmail.com>
synopsis: A library for simple INI-based configuration files.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <4.10'
  unordered-containers: ! '>=0.2.7 && <0.3'
  text: ! '>=1.2.2 && <1.3'
  megaparsec: ! '>=5.1.2 && <5.2'
  config-ini: -any
  transformers: ! '>=0.5.2 && <0.6'
all-versions:
- '0.1.0.0'
author: Getty Ritter <gettyritter@gmail.com>
latest: '0.1.0.0'
description-type: haddock
description: ! 'The @config-ini@ library is a small monadic language

  for writing simple configuration languages with convenient,

  human-readable error messages.


  > parseConfig :: IniParser (Text, Int, Bool)

  > parseConfig = section "NETWORK" $ do

  >   user <- field        "user"

  >   port <- fieldOf      "port" number

  >   enc  <- fieldFlagDef "encryption" True

  >   return (user, port, enc)'
license-name: BSD3
