changelog-type: ''
hash: fe79584c3ed3bf3f1ed93683d3e43c7af79b0afab876a03a268cde470dfbf447
synopsis: Simple data type for application configuration.
changelog: ''
all-versions:
- '0.1'
- '0.1.1'
latest: '0.1.1'
description-type: haddock
description: Simple data type to store Typeable values.
