homepage: https://gitlab.com/guyonvarch/config-manager
changelog-type: ''
hash: 3adccd9f270ff19729b4e2e40b2d95edb0d5612a02e7048d9f93fa5e10fb7eed
test-bench-deps:
  test-framework-hunit: -any
  test-framework: -any
  base: -any
  unordered-containers: -any
  text: -any
  HUnit: -any
  config-manager: -any
  temporary: -any
  directory: -any
maintainer: joris@guyonvarch.me
synopsis: Configuration management
changelog: ''
basic-deps:
  base: <5
  unordered-containers: -any
  text: -any
  filepath: -any
  parsec: -any
all-versions:
- '0.0.0.1'
author: Joris Guyonvarch
latest: '0.0.0.1'
description-type: haddock
description: ! 'A configuration management library which supports:


  * name-value bindings,


  * required or optional imports,


  * and comments.'
license-name: GPL-3
