changelog-type: ''
hash: e59fb22c20cee9a363917db8d812880c569c706fb3983d8147601f4c5be3dd6a
synopsis: A simple config library
changelog: ''
all-versions:
- '0.1.0.0'
- '0.2.0.0'
latest: '0.2.0.0'
description-type: haddock
description: A simple config library.
