changelog-type: ''
hash: 9296bf5bb6426899f17a4bd179dc314d6980656dee996fb8df0a4924905f8fb3
synopsis: Simple config file parser generator
changelog: ''
all-versions:
- '1.0.0'
- '1.1.0'
- '1.1.1.0'
- '1.2.0'
- '1.2.1'
- '1.2.2'
- '1.2.2.1'
latest: '1.2.2.1'
description-type: haddock
description: Simple config file parser generator
