homepage: https://github.com/phadej/servant-swagger-ui#readme
changelog-type: ''
hash: e4d0eb06454b01ba19929369a387b64b7c8851717ca528c43a9589a1222463b6
test-bench-deps:
  warp: ! '>=3.0.13.1 && <3.3'
  bytestring: ! '>=0.10.4.0 && <0.11'
  servant-swagger-ui: -any
  wai: ! '>=3.0.3.0 && <3.3'
  base: ! '>=4.7 && <4.10'
  blaze-markup: ! '>=0.7.0.2 && <0.8'
  text: ! '>=1.2.0.6 && <1.3'
  filepath: ! '>=1.3.0.2 && <1.5'
  servant-swagger: ! '>=1.0.3 && <1.2'
  servant-server: ! '>=0.4.4.5 && <0.8'
  servant: ! '>=0.4.4.5 && <0.8'
  servant-blaze: ! '>=0.4.4.5 && <0.8'
  lens: ! '>=4.7.0.1 && <4.15'
  base-compat: ! '>=0.6.0 && <0.10'
  swagger2: ! '>=2.0.1 && <2.2'
  file-embed: ! '>=0.0.9 && <0.1'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  aeson: ! '>=0.8.0.2 && <0.12'
  template-haskell: ! '>=2.9 && <2.12'
  http-media: ! '>=0.6.2 && <0.8'
  directory: ! '>=1.2.1.0 && <1.3'
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: Servant swagger ui
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  base: ! '>=4.7 && <4.10'
  blaze-markup: ! '>=0.7.0.2 && <0.8'
  text: ! '>=1.2.0.6 && <1.3'
  filepath: ! '>=1.3.0.2 && <1.5'
  servant-swagger: ! '>=1.0.3 && <1.2'
  servant-server: ! '>=0.4.4.5 && <0.8'
  servant: ! '>=0.4.4.5 && <0.8'
  servant-blaze: ! '>=0.4.4.5 && <0.8'
  swagger2: ! '>=2.0.1 && <2.2'
  file-embed: ! '>=0.0.9 && <0.1'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  template-haskell: ! '>=2.9 && <2.12'
  http-media: ! '>=0.6.2 && <0.8'
  directory: ! '>=1.2.1.0 && <1.3'
all-versions:
- '0.1.0.2.1.4'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.1.0.2.1.4'
description-type: markdown
description: ! '# servant-swagger-ui


  > Servant support for yaml


  [![Build Status](https://travis-ci.org/phadej/servant-swagger-ui.svg?branch=master)](https://travis-ci.org/phadej/servant-swagger-ui)

  [![Hackage](https://img.shields.io/hackage/v/servant-swagger-ui.svg)](http://hackage.haskell.org/package/servant-swagger-ui)

  [![Stackage LTS 5](http://stackage.org/package/servant-swagger-ui/badge/lts-5)](http://stackage.org/lts-5/package/servant-swagger-ui)

  [![Stackage Nightly](http://stackage.org/package/servant-swagger-ui/badge/nightly)](http://stackage.org/nightly/package/servant-swagger-ui)


  ## Example


  ![example screenshot](https://raw.githubusercontent.com/phadej/servant-swagger-ui/master/screenshot.png)


  Check [`example/Main.hs`](https://github.com/phadej/servant-swagger-ui/blob/master/example/Main.hs)
  for an example.

'
license-name: BSD3
