homepage: https://github.com/martyall/servant-zeppelin#readme
changelog-type: ''
hash: 1a111fb90558f2a09959e45ed5d794dfef26d98684f82dd051346456adf42d0b
test-bench-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  servant-zeppelin-swagger: ! '>=0.1.0.2 && <0.2'
  base: ! '>=4.9.1.0 && <4.10'
  hspec: ! '>=2.4.3 && <2.5'
  servant-swagger: ! '>=1.1.2.1 && <1.2'
  servant: ==0.10.*
  containers: ! '>=0.5.7.1 && <0.6'
  lens: ! '>=4.15.1 && <4.16'
  servant-zeppelin: ! '>=0.1.0.2 && <0.2'
  swagger2: ! '>=2.1.4 && <2.2'
  aeson: ! '>=1.0.2.1 && <1.1'
maintainer: martin[dot]allen26[at]gmail.com
synopsis: Swagger instances for servant-zeppelin combinators.
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  base: ! '>=4.7 && <5'
  text: ! '>=1.2.2.1 && <1.3'
  servant-swagger: ! '>=1.1.2.1 && <1.2'
  servant: ==0.10.*
  singletons: ==2.2.*
  lens: ! '>=4.15.1 && <4.16'
  servant-zeppelin: ! '>=0.1.0.2 && <0.2'
  swagger2: ! '>=2.1.4 && <2.2'
  aeson: ! '>=1.0.2.1 && <1.1'
all-versions:
- '0.1.0.0'
- '0.1.0.2'
author: Martin Allen, Ben Weitzman
latest: '0.1.0.2'
description-type: markdown
description: ! '# servant-side-loaded

'
license-name: BSD3
