homepage: ''
changelog-type: ''
hash: f31eee4e78cfdbf703cec1f48ac4649afa6631fcba415312c5e9491f26d224b8
test-bench-deps: {}
maintainer: djohnson.m@gmail.com
synopsis: Swagger
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  uuid: -any
  servant: -any
  containers: -any
  lens: -any
  hashable: -any
  aeson: -any
all-versions:
- '0.0.0.0'
author: David Johnson
latest: '0.0.0.0'
description-type: haddock
description: This is an experimental release, this API is subject to change at any
  moment.
license-name: BSD3
