homepage: http://github.com/plow-technologies/servant-auth#readme
changelog-type: ''
hash: 080a009174aab5950ac51c6d58a6971cf039705cabf6c1b152d18874fbd8572b
test-bench-deps:
  base: ! '>=4.7 && <4.10'
  hspec: ! '>2 && <3'
  text: -any
  servant-auth-swagger: -any
  doctest: ! '>=0.9 && <0.12'
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.2.*
  swagger2: ==2.*
  QuickCheck: ! '>=2.8 && <2.10'
  Glob: ! '>=0.7 && <0.8'
  yaml: ==0.8.*
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: ''
basic-deps:
  base: ! '>=4.7 && <4.10'
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.2.*
  swagger2: ! '>=2 && <3'
all-versions:
- '0.2.6.0'
- '0.2.6.1'
author: Julian K. Arni
latest: '0.2.6.1'
description-type: haddock
description: Please see README.md
license-name: BSD3
