homepage: http://github.com/plow-technologies/servant-auth#readme
changelog-type: ''
hash: e438561e4a1adfe066e2fc6b8d443ceee4b943c8dddd534e8403ecc1f52d3b04
test-bench-deps:
  base: ! '>=4.7 && <4.10'
  hspec: ! '>2 && <3'
  text: -any
  servant-auth-swagger: -any
  doctest: ! '>=0.9 && <0.12'
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.2.*
  swagger2: ==2.*
  QuickCheck: ! '>=2.8 && <2.9'
  Glob: ! '>=0.7 && <0.8'
  yaml: ==0.8.*
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: ''
basic-deps:
  base: ! '>=4.7 && <4.10'
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.2.*
  swagger2: ! '>=2 && <3'
all-versions:
- '0.2.6.0'
author: Julian K. Arni
latest: '0.2.6.0'
description-type: haddock
description: Please see README.md
license-name: BSD3
