homepage: ''
changelog-type: ''
hash: 48d777095cf38174a1a1853ddac7b4187a9ef01c5536c6ad49f8ede4c9bb8c66
test-bench-deps: {}
maintainer: djohnson.m@gmail.com
synopsis: Swagger
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  uuid: -any
  servant: -any
  containers: -any
  lens: -any
  hashable: -any
  aeson: -any
all-versions:
- '0.0.0.0'
- '0.0.0.1'
author: David Johnson
latest: '0.0.0.1'
description-type: haddock
description: This is an experimental release, this API is subject to change at any
  moment.
license-name: BSD3
