homepage: https://github.com/dmjio/servant-swagger
changelog-type: ''
hash: fa659c1a2e8224c9ba307ef14509fc384b5ea9b068f46c35e5c6c8a23d8bd751
test-bench-deps:
  base: ==4.*
  time: -any
  hspec: -any
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  swagger2: ! '>=1 && <2'
  aeson-qq: -any
  aeson: -any
maintainer: djohnson.m@gmail.com
synopsis: Generate Swagger specification for your servant API.
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  servant: -any
  lens: -any
  swagger2: ! '>=1 && <2'
  aeson: -any
  http-media: -any
all-versions:
- '0.0.0.0'
- '0.0.0.1'
- '0.1'
- '0.1.1'
- '0.1.2'
author: David Johnson
latest: '0.1.2'
description-type: markdown
description: ! "# servant-swagger\n\n[![Build Status](https://travis-ci.org/haskell-servant/servant-swagger.svg?branch=master)](https://travis-ci.org/haskell-servant/servant-swagger)\n[![Hackage](https://img.shields.io/hackage/v/servant-swagger.svg)](http://hackage.haskell.org/package/servant-swagger)\n[![Stackage
  LTS](http://stackage.org/package/servant-swagger/badge/lts)](http://stackage.org/lts/package/servant-swagger)\n[![Stackage
  Nightly](http://stackage.org/package/servant-swagger/badge/nightly)](http://stackage.org/nightly/package/servant-swagger)\n\nThis
  project converts [servant](https://github.com/haskell-servant/servant) APIs into
  Swagger 2.0 conforming json.\n\n![servant-swagger robot](http://s16.postimg.org/rndz1wbyt/servant.png)\n\n<hr>\n\nGiven
  the following `servant` API, `servant-swagger` generates the following json.\n\n###
  [Input](example/File.hs)\n\n```haskell\n{-# LANGUAGE DataKinds                  #-}\n{-#
  LANGUAGE DeriveGeneric              #-}\n{-# LANGUAGE GeneralizedNewtypeDeriving
  #-}\n{-# LANGUAGE OverloadedStrings          #-}\n{-# LANGUAGE TypeOperators              #-}\nmodule
  Main where\n\nimport Control.Lens\nimport Data.Aeson\nimport qualified Data.ByteString.Lazy.Char8
  as BL8\nimport Data.Proxy\nimport Data.Swagger\nimport GHC.Generics\nimport Servant\nimport
  Servant.Swagger\n\n-- Types\ndata Todo = Todo\n  { created     :: Int\n  , description
  :: String\n  } deriving (Show, Eq, Generic)\n\ninstance ToJSON Todo\n\nnewtype TodoId
  = TodoId String deriving (FromText, Generic)\n\n-- API\ntype API = \"todo\" :> Capture
  \"id\" TodoId :> Get '[JSON] Todo\n\n-- Swagger Doc\nswagDoc :: Swagger\nswagDoc
  = toSwagger (Proxy :: Proxy API)\n  & info.infoTitle   .~ \"Todo API\"\n  & info.infoVersion
  .~ \"1.0\"\n  & info.infoDescription ?~ \"This is an API that tests servant-swagger
  support for a Todo\"\n  & info.infoLicense ?~ License \"MIT\" (Just (URL \"http://mit.com\"))\n\n--
  Documentation and annotations\ninstance ToParamSchema TodoId\n\ninstance ToSchema
  Todo where\n  declareNamedSchema proxy = do\n    (name, schema) <- genericDeclareNamedSchema
  defaultSchemaOptions proxy\n    return (name, schema\n      & schemaDescription
  ?~ \"This is some real Todo right here\"\n      & schemaExample ?~ toJSON (Todo
  100 \"get milk\"))\n\n-- Main, create swaggger.json\nmain :: IO ()\nmain = BL8.writeFile
  \"swagger.json\" (encode swagDoc)\n```\n\n### Output\n\n```json\n{\n   \"swagger\":\"2.0\",\n
  \  \"info\":{\n      \"version\":\"1.0\",\n      \"title\":\"Todo API\",\n      \"license\":{\n
  \        \"url\":\"http://mit.com\",\n         \"name\":\"MIT\"\n      },\n      \"description\":\"This
  is an API that tests servant-swagger support for a Todo\"\n   },\n   \"definitions\":{\n
  \     \"Todo\":{\n         \"example\":{\n            \"created\":100,\n            \"description\":\"get
  milk\"\n         },\n         \"required\":[\n            \"created\",\n            \"description\"\n
  \        ],\n         \"type\":\"object\",\n         \"description\":\"This is some
  real Todo right here\",\n         \"properties\":{\n            \"created\":{\n
  \              \"maximum\":9223372036854775807,\n               \"minimum\":-9223372036854775808,\n
  \              \"type\":\"integer\"\n            },\n            \"description\":{\n
  \              \"type\":\"string\"\n            }\n         }\n      }\n   },\n
  \  \"paths\":{\n      \"/todo/{id}\":{\n         \"get\":{\n            \"responses\":{\n
  \              \"404\":{\n                  \"description\":\"`id` not found\"\n
  \              },\n               \"200\":{\n                  \"schema\":{\n                     \"$ref\":\"#/definitions/Todo\"\n
  \                 },\n                  \"description\":\"\"\n               }\n
  \           },\n            \"produces\":[\n               \"application/json\"\n
  \           ],\n            \"parameters\":[\n               {\n                  \"required\":true,\n
  \                 \"in\":\"path\",\n                  \"name\":\"id\",\n                  \"type\":\"string\"\n
  \              }\n            ]\n         }\n      }\n   }\n}\n```\n\n## Try it
  out\n\nAll generated swagger specifications can be interactively viewed on [Swagger
  Editor](http://editor.swagger.io/).\n\nReady-to-use specification can be served
  as JSON and interactive API documentation\ncan be displayed using [Swagger UI](https://github.com/swagger-api/swagger-ui).\n\nMany
  Swagger tools, including server and client code generation for many languages, can
  be found on\n[Swagger's Tools and Integrations page](http://swagger.io/open-source-integrations/).\n\n##
  Contributing\n\nWe are happy to receive bug reports, fixes, documentation enhancements,
  and other improvements.\n\nPlease report bugs via the [github issue tracker](https://github.com/dmjio/servant-swagger/issues).\n\n"
license-name: BSD3
