homepage: https://github.com/martyall/servant-zeppelin#readme
changelog-type: ''
hash: d529f34bb91d1f36b1df21fec2903637d4190e9142723ec56fe4986e9caefa80
test-bench-deps:
  insert-ordered-containers: -any
  servant-zeppelin-swagger: -any
  base: -any
  hspec: -any
  servant-swagger: -any
  servant: -any
  containers: -any
  lens: -any
  servant-zeppelin: -any
  swagger2: -any
  aeson: -any
maintainer: martin[dot]allen26[at]gmail.com
synopsis: Swagger instances for servant-zeppelin combinators.
changelog: ''
basic-deps:
  insert-ordered-containers: -any
  base: ! '>=4.7 && <5'
  text: -any
  servant-swagger: ! '>=1.1.2.1'
  servant: -any
  singletons: -any
  lens: -any
  servant-zeppelin: -any
  swagger2: -any
  aeson: -any
all-versions:
- '0.1.0.0'
author: Martin Allen, Ben Weitzman
latest: '0.1.0.0'
description-type: markdown
description: ! '# servant-side-loaded

'
license-name: BSD3
