homepage: https://github.com/agrafix/highjson
changelog-type: ''
hash: 06769925b95fe9395a91b0ab4729d97538c2a9541c9e80f20ddf808d516598d9
test-bench-deps:
  bytestring: -any
  base: -any
  hspec: ! '>=2.0'
  text: -any
  lens: -any
  swagger2: -any
  QuickCheck: ! '>=2.8'
  highjson: -any
  aeson: -any
  highjson-swagger: -any
maintainer: Alexander Thiemann <mail@athiemann.net>
synopsis: Derive swagger instances from highjson specs
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2'
  base: ! '>=4.8 && <5'
  text: -any
  hvect: -any
  lens: -any
  swagger2: ! '>=2.1.3'
  highjson: ! '>=0.3'
all-versions:
- '0.3.0.0'
author: Alexander Thiemann <mail@athiemann.net>
latest: '0.3.0.0'
description-type: haddock
description: Derive swagger instances from highjson specs
license-name: MIT
