homepage: ''
changelog-type: ''
hash: 70d5382042b4b9f7500a5e5eb1c143aa28c68d9755ec121908c304e56af76345
test-bench-deps: {}
maintainer: danburton.email@gmail.com
synopsis: The Haskell Tool Stack
changelog: ''
basic-deps:
  base: ! '>=4.8 && <5'
all-versions:
- '0.0.0'
author: Dan Burton
latest: '0.0.0'
description-type: haddock
description: ''
license-name: MIT
