homepage: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)
changelog-type: ''
hash: 6cfcd8c9d1aba60f421616e585513e9a6177c7654606b27b1fd85110bbe8dcd8
test-bench-deps: {}
maintainer: rwlock404@yahoo.com
synopsis: Stack data structure type
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
all-versions:
- '0.1.0'
- '0.2.0'
author: Robert Walker
latest: '0.2.0'
description-type: haddock
description: Please see README.md
license-name: BSD3
