homepage: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)
changelog-type: ''
hash: 3d5edf731a665f3d971500598e60de509ae8410d65c5d3526868361b6d05598a
test-bench-deps: {}
maintainer: rwlock404@yahoo.com
synopsis: Stack data structure
changelog: ''
basic-deps:
  stm: ! '>=2.4.4.1 && <2.5'
  base: ! '>=4.7 && <5'
  nats: ! '>=1.1.1 && <1.2'
all-versions:
- '0.1.0'
- '0.2.0'
- '0.3.0'
- '0.3.1'
- '0.3.2'
author: Robert Walker
latest: '0.3.2'
description-type: haddock
description: ! 'A stack is a basic data structure that can be logically thought as
  linear structure represented by a real physical stack or pile, a structure where
  insertion and deletion of items takes place at one end called top of the stack.


  <<https://upload.wikimedia.org/wikipedia/commons/b/b4/Lifo_stack.png>>'
license-name: BSD3
