homepage: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)
changelog-type: ''
hash: 23e8ac23f5f28b6d18e87c48cd7a7122307b91d98a34fd678a35df2807902525
test-bench-deps: {}
maintainer: rwlock404@yahoo.com
synopsis: Stack data structure type
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
all-versions:
- '0.1.0'
- '0.2.0'
author: Robert Walker
latest: '0.2.0'
description-type: haddock
description: Please see README.md
license-name: BSD3
