homepage: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)
changelog-type: ''
hash: b9bcfa1132bab6411d5f19eaad9498689a74230f86927d5ef2e7648c92e91c79
test-bench-deps: {}
maintainer: rwlock404@yahoo.com
synopsis: Stack data structure type
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
all-versions:
- '0.1.0'
author: Robert Walker
latest: '0.1.0'
description-type: haddock
description: Please see README.md
license-name: BSD3
