homepage: ! 'https://github.com/commercialhaskell/stack

  test/package-dump/ghc-7.8.txt

  test/package-dump/ghc-7.10.txt'
changelog-type: markdown
hash: dae6830d42c5f9c7c13efea533f2184822d90a4d0e52f2d001df7e32d8b14982
test-bench-deps:
  exceptions: -any
  Cabal: -any
  path: -any
  base: ! '>=4.7 && <5'
  hspec: -any
  filepath: -any
  conduit: -any
  conduit-extra: -any
  containers: -any
  monad-logger: -any
  transformers: -any
  temporary: -any
  http-conduit: -any
  stack: -any
  resourcet: -any
  directory: -any
  cryptohash: -any
maintainer: chrisdone@fpcomplete.com
synopsis: The Haskell Tool Stack
changelog: ! '## 0.0.2


  * Fix some Windows specific bugs [#216](https://github.com/commercialhaskell/stack/issues/216)

  * Improve output for package index updates [#227](https://github.com/commercialhaskell/stack/issues/227)

  * Automatically update indices as necessary [#227](https://github.com/commercialhaskell/stack/issues/227)

  * --verbose flag [#217](https://github.com/commercialhaskell/stack/issues/217)

  * Remove packages (HTTPS and Git) [#199](https://github.com/commercialhaskell/stack/issues/199)

  * Config values for system-ghc and install-ghc

  * Merge `stack deps` functionality into `stack build`

  * `install` command [#153](https://github.com/commercialhaskell/stack/issues/153)
  and [#272](https://github.com/commercialhaskell/stack/issues/272)

  * overriding architecture value (useful to force 64-bit GHC on Windows, for example)

  * Overhauled test running (allows cycles, avoids unnecessary recompilation, etc)


  ## 0.0.1


  * First public release, beta quality

'
basic-deps:
  http-client: ! '>=0.4.9'
  conduit-combinators: ! '>=0.3.1'
  exceptions: ! '>=0.8.0.2'
  void: ! '>=0.7'
  streaming-commons: ! '>=0.1.10.0'
  either: -any
  bytestring: ! '>=0.10.4.0'
  unix: ! '>=2.7.0.1'
  split: -any
  stm: ! '>=2.4.4'
  Cabal: ! '>=1.18.1.5'
  path: ! '>=0.5.0'
  base: ! '>=4.7 && <5'
  time: ! '>=1.4.2'
  base64-bytestring: -any
  persistent: ! '>=2.1.2'
  unordered-containers: ! '>=0.2.5.1'
  text: ! '>=1.2.0.4'
  persistent-template: ! '>=2.1.1'
  enclosed-exceptions: -any
  monad-loops: ! '>=0.4.2.1'
  monad-control: -any
  filepath: ! '>=1.3.0.2'
  process: ! '>=1.2.0.0'
  async: ! '>=2.0.2'
  lifted-base: -any
  conduit: ! '>=1.2.4'
  conduit-extra: ! '>=1.1.7.1'
  fast-logger: ! '>=2.3.1'
  containers: ! '>=0.5.5.1'
  vector-binary-instances: -any
  tar: ! '>=0.4.1.0'
  bifunctors: ! '>=4.2.1'
  binary: ! '>=0.7'
  old-locale: ! '>=1.0.0.6'
  http-client-tls: ! '>=0.2.2'
  cryptohash-conduit: -any
  zlib: ! '>=0.5.4.2'
  mtl: ! '>=2.1.3.1'
  optparse-simple: ! '>=0.0.3'
  hashable: ! '>=1.2.3.2'
  transformers-base: ! '>=0.4.4'
  monad-logger: ! '>=0.3.13.1'
  base16-bytestring: -any
  attoparsec: ! '>=0.12.1.5'
  transformers: ! '>=0.3.0.0'
  temporary: ! '>=1.2.0.3'
  optparse-applicative: ! '>=0.11.0.2'
  deepseq: -any
  http-conduit: ! '>=2.1.5'
  stack: -any
  resourcet: ! '>=1.1.4.1'
  http-types: ! '>=0.8.6'
  pretty: -any
  persistent-sqlite: ! '>=2.1.4'
  aeson: ! '>=0.8.0.2'
  template-haskell: -any
  safe: ! '>=0.3'
  yaml: ! '>=0.8.10.1'
  vector: ! '>=0.10.12.3'
  directory: ! '>=1.2.1.0'
  cryptohash: ! '>=0.11.6'
all-versions:
- '0.0.0'
- '0.0.1'
- '0.0.2'
author: Chris Done
latest: '0.0.2'
description-type: markdown
description: ! "## The Haskell Tool Stack\n\n[![Build Status](https://travis-ci.org/commercialhaskell/stack.svg?branch=master)](https://travis-ci.org/commercialhaskell/stack)\n\n`stack`
  is a cross-platform program for developing Haskell\nprojects. It is aimed at Haskellers
  both new and experienced.\n\n<img src=\"http://i.imgur.com/WW69oTj.gif\" width=\"50%\"
  align=\"right\">\n\nIt features:\n\n* Installing GHC automatically.\n* Installing
  packages needed for your project.\n* Building your project.\n* Testing your project.\n*
  Benchmarking your project.\n\n#### How to install\n\nDownloads are available by
  operating system:\n\n* [Windows](https://github.com/commercialhaskell/stack/wiki/Downloads#windows)\n*
  [OS X](https://github.com/commercialhaskell/stack/wiki/Downloads#os-x)\n* [Ubuntu](https://github.com/commercialhaskell/stack/wiki/Downloads#ubuntu)\n*
  [Arch Linux](https://github.com/commercialhaskell/stack/wiki/Downloads#arch-linux)\n*
  [Linux (general)](https://github.com/commercialhaskell/stack/wiki/Downloads#linux)\n\n####
  How to use\n\nGo into a Haskell project directory and run `stack build`. This will\ndo
  the following:\n\n* Automatically create a stack configuration file in the current\n
  \ directory.\n* Figure out what Stackage release (LTS or nightly) is appropriate\n
  \ for the dependencies.\n* Download and install GHC.\n* Download the package index.\n*
  Download and install all necessary dependencies for the project.\n* Build and install
  the project.\n\nRun `stack` for a complete list of commands.\n\n#### Architecture\n\nA
  full description of the architecture\n[is available here](https://github.com/commercialhaskell/stack/wiki/Architecture).\n\n####
  Questions, Feedback, Discussion\n\n* For frequently asked questions about detailed
  or specific use-cases,\n  please see\n  [the FAQ](https://github.com/commercialhaskell/stack/wiki/FAQ).\n*
  For general questions, comments, feedback and support please write\n  to\n  [the
  Commercial Haskell mailing list](https://groups.google.com/d/forum/commercialhaskell).\n*
  For bugs, issues, or requests please\n  [open an issue](https://github.com/commercialhaskell/stack/issues/new).\n\n####
  Why stack?\n\nstack is a project of the [Commercial Haskell](http://commercialhaskell.com/)\ngroup,
  spearheaded by [FP Complete](https://www.fpcomplete.com/). It is\ndesigned to answer
  the needs of commercial Haskell users, hobbyist Haskellers,\nand individuals and
  companies thinking about starting to use Haskell. It is\nintended to be easy to
  use for newcomers, while providing the customizability\nand power experienced developers
  need.\n\nWhile stack itself has been around since June of 2015, it is based on codebases\nused
  by FP Complete for its corporate customers and internally for years prior.\nstack
  is a refresh of that codebase combined with other open source efforts\nlike [stackage-cli](https://github.com/fpco/stackage-cli)
  to meet the needs of\nusers everywhere.\n\nA large impetus for the work on stack
  was a [large survey of people interested\nin\nHaskell](https://www.fpcomplete.com/blog/2015/05/thousand-user-haskell-survey),\nwhich
  rated build issues as a major concern. The stack team hopes that stack\ncan address
  these concerns.\n"
license-name: BSD3
