changelog-type: ''
hash: 440a1bcbbc592651376b2c158c80e1f031d1d01efad80846c3262d3a4283b120
synopsis: Global mutable configuration
changelog: ''
all-versions:
- '0.1.0'
- '0.2.0'
- '0.2.1'
- '0.3.0'
- '0.3.1'
latest: '0.3.1'
description-type: haddock
description: ! '@Data.Global.Config@ provides brain-free pattern to work with global

  configurations. Use wisely.'
