changelog-type: ''
hash: 9d9684b65a7722f919aaa85b5f93f720b11cbf2231082ea3d03c260192b3d25d
synopsis: DEPRECATED! You should use standard Snap >= 0.9 "environments" functionality.
  It provided ability to easly read configuration based on given app environment given
  at command line, envs are defined in app configuration file
changelog: ''
all-versions:
- '0.1'
- '0.1.1'
latest: '0.1.1'
description-type: haddock
description: ''
