changelog-type: ''
hash: e3cff288b7cec9a09bf748c3496f834c15ee14cf2869bc073de66356261dae3f
synopsis: Methods to manipulate Configurator objects for Snap & Snaplets
changelog: ''
all-versions:
- '0.1.0.0'
latest: '0.1.0.0'
description-type: haddock
description: Methods to manipulate Configurator objects for Snap & Snaplets
