homepage: http://www.keera.es/blog/community/
changelog-type: ''
hash: 20d6e1b63fed2f744af876fa4bf6e98a1e1abbdb3d29f1804068511165f66847
test-bench-deps: {}
maintainer: ivan.perez@keera.es
synopsis: Haskell on Rails - Reactive Values
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  contravariant: -any
all-versions:
- '0.0.3.4'
- '0.0.4'
- '0.1.0'
- '0.1.2.1'
author: Ivan Perez
latest: '0.1.2.1'
description-type: haddock
description: ''
license-name: BSD3
