homepage: ''
changelog-type: ''
hash: 12049d8491610c2789c61e4736586d3fa8b1122c5c7657647c3de8d21073ef80
test-bench-deps: {}
maintainer: mhitza@gmail.com
synopsis: Minimal ini like configuration library with a few extras
changelog: ''
basic-deps:
  base: ! '>=4.5 && <=4.8'
  filepath: <=1.3.0.2
  tconfig: ==0.5.2
  containers: <=0.5.6
  directory: <=1.2.1.0
all-versions:
- '0.1'
- '0.1.1'
author: Marius Ghita
latest: '0.1.1'
description-type: haddock
description: ! 'The module exported provides the ability to manage a configuration
  file in

  the users home directory (or the Windows equivalent). Where the configuration

  takes the form of key=value, without sections, that for example an \''.ini\''

  would have.


  The library simplifies serilization/deserialization of the configuration into

  a structure similar in behavior to a ''Map'', as well as an interactive way to

  fill in values for simple cases.


  Consider the following example, where a user would run the application for the

  first time, it would ask him for his name; however on a followup run it would

  just print a greeting with his name.


  > import System.Config.File

  >

  > main = withConfiguration ".apprc" $ \conf -> do

  >     let name = getV conf "name"

  >     case name of Just n  -> putStrLn $ "hello " ++ n

  >                  Nothing -> do conf'' <- fillInteractively conf [("name", acceptNonBlank)]

  >                                saveConfiguration conf'''
license-name: BSD3
