homepage: http://github.com/YoEight/deiko-config
changelog-type: ''
hash: 65e6a6d7eb066ad708303b749b9f8b966a217e4d21cbc2328fee513db6561f68
test-bench-deps: {}
maintainer: yo.eight@gmail.com
synopsis: Small and typesafe configuration library.
changelog: ''
basic-deps:
  exceptions: -any
  base: ! '>=4.7 && <5'
  text: ! '>=1.0 && <1.2'
  parsec: ! '>=3.1.2'
  array: ! '>=0.5 && <0.6'
  containers: -any
  mtl: ! '>=2.0 && <3.0'
  transformers: ! '>=0.3 && <0.6'
all-versions:
- '0.5.0.0'
author: Yorick Laupa
latest: '0.5.0.0'
description-type: haddock
description: Small and typesafe configuration library. The library provides good error
  messages and comes with a bottom-up typechecker in order to catch more configuration
  errors.
license-name: BSD3
