changelog-type: ''
hash: 8ef5019c062fc15b3b802652b365ab756430841759452cd90beb0748035f8b15
synopsis: Easy way to run doctests via cabal (no aeson dependency, uses configurator
  instead)
changelog: ''
all-versions:
- '0.1.0.6'
latest: '0.1.0.6'
description-type: haddock
description: doctest-discover provides an easy way to run doctests via cabal (uses
  configurator instead of aeson)
