changelog-type: ''
hash: a3ea580cb44eae79e59b0936e5bd14f47ba865607acef92d6fc25e61ed565aaf
synopsis: Easy trivial configuration for Redis
changelog: ''
all-versions:
- '0.0.1'
latest: '0.0.1'
description-type: haddock
description: ! 'Datatype to parse redis connection settings from file like


  > host: localhost                 # host name or address

  > port: 6379                      # you can specify either port

  > # socket: /run/redis.socket     # or unix socket path

  > # service: redis                # or service name

  > password: "pass"                # if not specified then no password used

  > database: 0                     # database number to connect to

  > max-connections: 5              # max connections in pool

  > max-idle-time: 30               # keep connection open for 30 seconds'
