homepage: https://bitbucket.org/s9gf4ult/hedis-config
changelog-type: markdown
hash: c04de9dac9fda9506e0d0fce43c3d9d1b85aeae4bdec7e0df2fc40ec0fe6bbac
test-bench-deps: {}
maintainer: s9gf4ult@gmail.com
synopsis: Easy trivial configuration for Redis
changelog: ! '# CHANGELOG


  ## 0.0.2

  ### Changed

  * relaxed upper base version constraints to `< 5`


  ## 0.0.1

  First working version

'
basic-deps:
  base: ! '>=4.6 && <5'
  time: -any
  text: -any
  scientific: -any
  hedis: ! '>=0.6'
  aeson: -any
all-versions:
- '0.0.1'
- '0.0.2'
author: Aleksey Uimanov
latest: '0.0.2'
description-type: markdown
description: ! "# How\n\nJust copy this\n\n```yaml\nhost: localhost                 #
  host name or address\nport: 6379                      # you can specify either port\n#
  socket: /run/redis.socket     # or unix socket path\n# service: redis                #
  or service name\npassword: \"pass\"                # if not specified then no password
  used\ndatabase: 0                     # database number to connect to\nmax-connections:
  5              # max connections in pool\nmax-idle-time: 30               # keep
  connection open for 30 seconds\n```\n\nto your config file, then\n\n```haskell\nimport
  Data.Yaml\nimport Database.Redis.Config\n\nmain :: IO ()\nmain = do\n    conn <-
  decodeFile \"config/redis.yml\" >>= \\case\n        Nothing -> fail \"Could not
  parse redis.conf\"\n        Just conf -> connectRedis conf\n    run conn\n```\n\nThats
  all, you already working with Redis connection"
license-name: BSD3
