homepage: https://bitbucket.org/s9gf4ult/hedis-config
changelog-type: markdown
hash: a537c207f31765aec460668e22447949031edd81ad37aeabbbfab72b50837130
test-bench-deps: {}
maintainer: s9gf4ult@gmail.com
synopsis: Easy trivial configuration for Redis
changelog: ! "# CHANGELOG\n\n## 0.0.3\n### Changed\n* Empty password string will be
  nullified. Redis counts empty `AUTH` command as\n  error when no password is set.\n\n##
  0.0.2\n### Changed\n* relaxed upper base version constraints to `< 5`\n\n## 0.0.1\nFirst
  working version\n"
basic-deps:
  bytestring: -any
  base: ! '>=4.6 && <5'
  time: -any
  text: -any
  scientific: -any
  hedis: ! '>=0.6'
  aeson: -any
all-versions:
- '0.0.1'
- '0.0.2'
- '0.0.3'
author: Aleksey Uimanov
latest: '0.0.3'
description-type: markdown
description: ! "# How\n\nJust copy this\n\n```yaml\nhost: localhost                 #
  host name or address\nport: 6379                      # you can specify either port\n#
  socket: /run/redis.socket     # or unix socket path\n# service: redis                #
  or service name\npassword: \"pass\"                # if not specified then no password
  used\ndatabase: 0                     # database number to connect to\nmax-connections:
  5              # max connections in pool\nmax-idle-time: 30               # keep
  connection open for 30 seconds\n```\n\nto your config file, then\n\n```haskell\nimport
  Data.Yaml\nimport Database.Redis.Config\n\nmain :: IO ()\nmain = do\n    conn <-
  decodeFile \"config/redis.yml\" >>= \\case\n        Nothing -> fail \"Could not
  parse redis.conf\"\n        Just conf -> connectRedis conf\n    run conn\n```\n\nThats
  all, you already working with Redis connection"
license-name: BSD3
