homepage: https://github.com/ChrisPenner/rasa/
changelog-type: ''
hash: b29a26858dc748c9b6438d009f035cc6a6640f0297f2f85bef18be1e59467508
test-bench-deps: {}
maintainer: christopher.penner@gmail.com
synopsis: Example user config for Rasa
changelog: ''
basic-deps:
  rasa-ext-style: ! '>=0.1.3 && <0.2'
  rasa-ext-vim: ! '>=0.1.3 && <0.2'
  base: ! '>=4.8 && <5'
  rasa-ext-status-bar: ! '>=0.1.2 && <0.2'
  rasa-ext-views: ! '>=0.1.1 && <0.2'
  lens: ==4.14.*
  rasa-ext-logger: ! '>=0.1.2 && <0.2'
  rasa-ext-slate: ! '>=0.1.4 && <0.2'
  rasa-ext-files: ! '>=0.1.2 && <0.2'
  mtl: ! '>=2.2.1 && <2.3'
  rasa-ext-cursors: ! '>=0.1.4 && <0.2'
  rasa: ! '>=0.1.7 && <0.2'
all-versions:
- '0.1.0.0'
- '0.1.1'
- '0.1.2'
author: Chris Penner
latest: '0.1.2'
description-type: haddock
description: Example user config for Rasa
license-name: MIT
