homepage: https://github.com/ChrisPenner/rasa/
changelog-type: ''
hash: d4148f6b726a895a7d2aaff704abd7016137d80b51200239de056d63a8b70789
test-bench-deps: {}
maintainer: christopher.penner@gmail.com
synopsis: Example user config for Rasa
changelog: ''
basic-deps:
  rasa-ext-style: ! '>=0.1.1 && <0.2'
  rasa-ext-vim: ! '>=0.1.1 && <0.2'
  base: ! '>=4.8 && <5'
  rasa-ext-status-bar: ! '>=0.1.1 && <0.2'
  lens: ==4.14.*
  rasa-ext-logger: ! '>=0.1.1 && <0.2'
  rasa-ext-slate: ! '>=0.1.2 && <0.2'
  rasa-ext-bufs: ! '>=0.1.1 && <0.2'
  rasa-ext-files: ! '>=0.1.1 && <0.2'
  mtl: ! '>=2.2.1 && <2.3'
  rasa-ext-cursors: ! '>=0.1.1 && <0.2'
  rasa: ! '>=0.1.4 && <0.2'
all-versions:
- '0.1.0.0'
- '0.1.1'
author: Chris Penner
latest: '0.1.1'
description-type: haddock
description: Example user config for Rasa
license-name: MIT
