homepage: https://github.com/ChrisPenner/rasa/
changelog-type: ''
hash: 97f6b87a84505bf8f6f4710911f14770c23451bdb30ce5b2777f2adbbf950483
test-bench-deps: {}
maintainer: christopher.penner@gmail.com
synopsis: Example user config for Rasa
changelog: ''
basic-deps:
  rasa-ext-style: -any
  rasa-ext-vim: -any
  base: ! '>=4.7 && <5'
  rasa-ext-status-bar: -any
  lens: -any
  rasa-ext-logger: -any
  rasa-ext-slate: -any
  rasa-ext-files: -any
  mtl: -any
  rasa-ext-cursors: -any
  rasa: -any
all-versions:
- '0.1.0.0'
author: Chris Penner
latest: '0.1.0.0'
description-type: haddock
description: Example user config for Rasa
license-name: MIT
