changelog-type: ''
hash: b1debcd7ff72135f4b62dd7cb3929035f7a41a6f9dc987ea5cfbc315da047dc4
test-bench-deps:
  test-framework-hunit: -any
  test-framework: -any
  base: ==4.*
  test-framework-quickcheck2: -any
  HUnit: -any
  test-framework-th: -any
  web-routes: -any
  QuickCheck: -any
synopsis: Library for maintaining correctness and composability of URLs within an
  application.
changelog: ''
basic-deps:
  bytestring: ! '>=0.9 && <0.11'
  split: -any
  base: ! '>=4 && <5'
  text: ! '>=0.11 && <1.3'
  parsec: ! '>=2 && <4'
  blaze-builder: ! '>=0.2 && <0.4'
  utf8-string: ! '>=0.3 && <0.4'
  ghc-prim: -any
  mtl: ! '>=2.0 && <2.3'
  http-types: ! '>=0.6 && <0.9'
all-versions:
- '0.22.0'
- '0.23.0'
- '0.23.1'
- '0.23.2'
- '0.23.4'
- '0.24.1'
- '0.25.1'
- '0.25.2'
- '0.25.3'
- '0.26.2'
- '0.26.3'
- '0.27.1'
- '0.27.2'
- '0.27.3'
- '0.27.4'
- '0.27.5'
- '0.27.6'
- '0.27.7'
- '0.27.8'
latest: '0.27.8'
description-type: haddock
description: A collection of types and functions that ensure that URLs generated by
  an application are valid. Need more properties here.
