homepage: ''
changelog-type: ''
hash: 853b4117cdc8e6059764fe8fcbdd9985e16dc221fe294df72253106567827010
test-bench-deps:
  bytestring: -any
  swagger: -any
  base: -any
  tasty-hunit: ! '>=0.8'
  tasty: ! '>=0.8'
  aeson: -any
maintainer: Toralf Wittner <tw@dtex.org>
synopsis: Implementation of swagger data model
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4 && <1.0'
  base: ==4.*
  time: ! '>=1.4 && <2.0'
  text: ! '>=0.11 && <2.0'
  transformers: ! '>=0.3 && <1.0'
  aeson: ! '>=0.6 && <1.0'
all-versions:
- '0.1'
- '0.2'
- '0.2.1'
- '0.2.2'
author: Toralf Wittner
latest: '0.2.2'
description-type: haddock
description: ! 'Implementation of Swagger specification version 1.2 as defined in

  <https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md>'
license-name: OtherLicense
