changelog-type: ''
hash: bc01047e53f742dd133dea57049997120d5e23c219943bc457c9d92c8bdd843f
synopsis: Implementation of swagger data model
changelog: ''
all-versions:
- '0.1'
- '0.2'
- '0.2.1'
- '0.2.2'
latest: '0.2.2'
description-type: haddock
description: ! 'Implementation of Swagger specification version 1.2 as defined in

  <https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md>'
