homepage: https://github.com/GetShopTV/swagger2
changelog-type: markdown
hash: 3b36eab8c915344e0d7948f41670e12ccb7c450bf667b217262d959283a48c9b
test-bench-deps:
  base: ==4.*
  unordered-containers: -any
  hspec: -any
  text: -any
  HUnit: -any
  swagger2: -any
  aeson-qq: -any
  QuickCheck: -any
  aeson: -any
  vector: -any
maintainer: nickolay@getshoptv.com
synopsis: Swagger 2.0 data model
changelog: ! "0.2\n---\n* Add `Data.Swagger.Lens`\n* Support references\n* Fixes:\n
  \   * Fix `FromJSON SwaggerHost` instance\n    * Add missing `Maybe`s for field
  types\n    * Decode petstore swagger.json successfully\n"
basic-deps:
  base: ==4.*
  unordered-containers: -any
  text: -any
  network: -any
  containers: -any
  lens: -any
  hashable: -any
  aeson: -any
  template-haskell: -any
  http-media: -any
all-versions:
- '0.1'
- '0.2'
author: Nickolay Kudasov
latest: '0.2'
description-type: markdown
description: ! '# swagger2


  [![Hackage](https://img.shields.io/hackage/v/swagger2.svg)](http://hackage.haskell.org/package/swagger2)

  [![Build Status](https://travis-ci.org/GetShopTV/swagger2.svg?branch=master)](https://travis-ci.org/GetShopTV/swagger2)


  Swagger 2.0 data model.

'
license-name: BSD3
