homepage: https://github.com/timbod7/haskell-chart/wiki
changelog-type: ''
hash: 7fe016cf57a0ba810decf18d88a2943be05ae0010ec4fd0e502a50eecffcd0d9
test-bench-deps: {}
maintainer: Tim Docker <tim@dockerz.net>
synopsis: A library for generating 2D Charts and Plots
changelog: ''
basic-deps:
  base: ! '>=3 && <5'
  data-default-class: <0.2
  time: -any
  array: -any
  lens: ! '>=3.9 && <4.16'
  old-locale: -any
  mtl: ! '>=2.0 && <2.3'
  operational: ! '>=0.2.2 && <0.3'
  colour: ! '>=2.2.1 && <2.4'
  vector: ! '>=0.9 && <0.12'
all-versions:
- '0.5'
- '0.6'
- '0.7'
- '0.8'
- '0.9'
- '0.10'
- '0.10.1'
- '0.10.2'
- '0.10.3'
- '0.11'
- '0.12'
- '0.13'
- '0.13.1'
- '0.14'
- '0.15'
- '0.16'
- '0.17'
- '1.0'
- '1.1'
- '1.2'
- '1.2.2'
- '1.2.3'
- '1.2.4'
- '1.3'
- '1.3.1'
- '1.3.2'
- '1.3.3'
- '1.4'
- '1.5'
- '1.5.1'
- '1.5.2'
- '1.5.3'
- '1.5.4'
- '1.6'
- '1.7'
- '1.7.1'
- '1.8'
- '1.8.1'
author: Tim Docker <tim@dockerz.net>
latest: '1.8.1'
description-type: haddock
description: ! 'A library for generating 2D Charts and Plots, with backends provided
  by

  Cairo (<http://hackage.haskell.org/package/Chart-cairo>)

  and

  Diagrams (<http://hackage.haskell.org/package/Chart-diagrams>).'
license-name: BSD3
