homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: f07b6305b1e4da83d8c0c87c309be5f3b2eed6a1e1bb7654a3f96c4d61454afa
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  tagged: ! '>=0.0 && <1'
  contravariant: ! '>=0.4 && <1.5'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.3'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
- '0.7.0.2'
- '0.7.1.0'
- '0.8.0.2'
- '0.8.0.3'
author: Purely Agile
latest: '0.8.0.3'
description-type: haddock
description: Product profunctors
license-name: BSD3
