homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 7452625e4f1b515275761695785ba59fe7d05fc31538b0c3ef1b9b547ab184b6
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.5'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.3'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
- '0.7.0.2'
author: Purely Agile
latest: '0.7.0.2'
description-type: haddock
description: Product profunctors
license-name: BSD3
