homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 01edcbebd6228c9fc9dbfbb173651e45cbca28cbd1dc55386a59dd24fb0a6ccd
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.4'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.2'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
author: Purely Agile
latest: '0.6.1'
description-type: haddock
description: Product profunctors
license-name: BSD3
