homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 04f9c23f6f4369cf19546028e51d1c81ef0e7399331b6ec527f6f31872862537
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.4'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.2'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
author: Purely Agile
latest: '0.6.3'
description-type: haddock
description: Product profunctors
license-name: BSD3
