homepage: http://github.com/khibino/haskell-product-isomorphic
changelog-type: ''
hash: e00c128322bf6be56e70eeda6bffa54109343d308e8ca5115d83a7e1e01e16b2
test-bench-deps: {}
maintainer: ex8k.hibino@gmail.com
synopsis: Weaken applicative functor on products
changelog: ''
basic-deps:
  base: <5
  th-data-compat: -any
  template-haskell: -any
all-versions:
- '0.0.1.0'
- '0.0.2.0'
- '0.0.3.0'
- '0.0.3.1'
author: Kei Hibino
latest: '0.0.3.1'
description-type: haddock
description: ! 'Weaken applicative functor which allows only product

  construction. Product constructions and deconstructions

  are always isomorphic.'
license-name: BSD3
