homepage: http://github.com/khibino/haskell-product-isomorphic
changelog-type: ''
hash: ba860e125badf6fb1f4093e6c48e442f61cbeb23577422561139f9217b3ffd36
test-bench-deps: {}
maintainer: ex8k.hibino@gmail.com
synopsis: Weaken applicative functor on products
changelog: ''
basic-deps:
  base: <5
  th-data-compat: -any
  template-haskell: -any
all-versions:
- '0.0.1.0'
- '0.0.2.0'
- '0.0.3.0'
author: Kei Hibino
latest: '0.0.3.0'
description-type: haddock
description: ! 'Weaken applicative functor which allows only product

  construction. Product constructions and deconstructions

  are always isomorphic.'
license-name: BSD3
