homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: ac8ac15500d9a5f4c678489d77c6abea03b24a704ceb235eecf9f49ef08da757
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.4'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.1'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
author: Purely Agile
latest: '0.6.1'
description-type: haddock
description: Product profunctors
license-name: BSD3
