homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: f9556571ee01ef282552fae6678026d6e9dbde79e60913c70326278f43b01db3
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.4'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.2'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
author: Purely Agile
latest: '0.6.3.1'
description-type: haddock
description: Product profunctors
license-name: BSD3
