homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: a249282eea8fad3325c86ec23d4b6af68ce46c2bd2a99d7be3272cfc94359ce1
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.5'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.3'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
author: Purely Agile
latest: '0.6.3.1'
description-type: haddock
description: Product profunctors
license-name: BSD3
