homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 98cd3c6ac3f78d4097bd1b8c7c1782b85bd05497938ce86d70cb0eb27b09359c
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  contravariant: ! '>=0.4 && <1.4'
  template-haskell: -any
  profunctors: ! '>=4.0 && <4.5'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
author: Purely Agile
latest: '0.6.1'
description-type: haddock
description: Product profunctors
license-name: BSD3
