changelog-type: ''
hash: 1223137a0f3df4d5dfae9d0ceaff9f4e33684b27a466b0534822c964c66521bb
synopsis: product-profunctors
changelog: ''
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
latest: '0.6.1'
description-type: haddock
description: Product profunctors
