homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 75773f30607faa502a996a2bb088f39e09963f2436a5a59405e54313d902c35b
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  tagged: ! '>=0.0 && <1'
  contravariant: ! '>=0.4 && <1.5'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.3'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
- '0.7.0.2'
- '0.7.1.0'
- '0.8.0.2'
author: Purely Agile
latest: '0.8.0.2'
description-type: haddock
description: Product profunctors
license-name: BSD3
