homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: ''
hash: 56aad124ad4489c1e22a606800ebc4bd6e30ce1a3b66a0b42dc415a6e002bae5
test-bench-deps:
  base: ! '>=4 && <5'
  product-profunctors: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ''
basic-deps:
  base: ! '>=4.8 && <5'
  tagged: ! '>=0.0 && <1'
  contravariant: ! '>=0.4 && <1.5'
  template-haskell: -any
  profunctors: ! '>=4.0 && <5.3'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
- '0.7.0.2'
- '0.7.1.0'
author: Purely Agile
latest: '0.7.1.0'
description-type: haddock
description: Product profunctors
license-name: BSD3
