homepage: https://github.com/fimad/prometheus-haskell
changelog-type: ''
hash: e6b826cf03975bf7d827ac78b512357602ee953a9ea61b861a1a824023a3d5cd
test-bench-deps:
  bytestring: -any
  stm: -any
  base: ! '>=4.6 && <4.8'
  time: -any
  hspec: -any
  criterion: ! '>=1.1'
  doctest: -any
  random-shuffle: -any
  containers: -any
  utf8-string: -any
  atomic-primops: -any
  mtl: -any
  transformers: -any
  random: -any
  QuickCheck: -any
  prometheus-client: -any
maintainer: willcoster@gmail.com
synopsis: Haskell client library for http://prometheus.io.
changelog: ''
basic-deps:
  bytestring: ! '>=0.9'
  stm: ! '>=2.3'
  base: ! '>=4.6 && <4.8'
  time: -any
  containers: -any
  utf8-string: -any
  atomic-primops: ! '>=0.4'
  mtl: ! '>=2'
  transformers: -any
all-versions:
- '0.1.0.0'
author: Will Coster
latest: '0.1.0.0'
description-type: haddock
description: Haskell client library for http://prometheus.io.
license-name: Apache-2.0
