homepage: http://github.com/LukeHoersten/prometheus#readme
changelog-type: ''
hash: 6bfed602b168ebd3a69757e75ecca4eda3c02219f222a24cd092b15972dd352f
test-bench-deps: {}
maintainer: luke@hoersten.org
synopsis: Prometheus Haskell Client
changelog: ''
basic-deps:
  warp: ! '>=3.2 && <3.3'
  bytestring: ! '>=0.10 && <0.11'
  wai: ! '>=3.2 && <3.3'
  base: ! '>=4.7 && <5.0'
  text: ! '>=1.2 && <1.3'
  containers: ! '>=0.5 && <0.6'
  atomic-primops: ! '>=0.8 && <0.9'
  mtl: ! '>=2.2 && <2.3'
  transformers: ! '>=0.4 && <0.5'
  http-types: ! '>=0.9 && <0.10'
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.0.2'
- '0.1.0.3'
author: Luke Hoersten
latest: '0.1.0.3'
description-type: haddock
description: Idiomatic Haskell client for Prometheus.io monitoring.
license-name: BSD3
