changelog-type: ''
hash: d11fde80081897b5d62bebca8d3c49b2c4d742113fd7caca72644f82667af8b8
synopsis: Efficient routing for Yesod. (deprecated)
changelog: ''
all-versions:
- '0.0.1'
- '1.0.0'
- '1.0.1'
- '1.0.1.1'
- '1.0.1.2'
- '1.1.0'
- '1.1.0.1'
- '1.1.0.2'
- '1.1.1'
- '1.1.1.1'
- '1.1.2'
- '1.2.0'
- '1.2.0.1'
- '1.2.0.2'
- '1.2.0.3'
- '1.2.0.4'
- '1.2.0.5'
- '1.2.0.6'
- '1.2.0.7'
latest: '1.2.0.7'
description-type: haddock
description: Provides an efficient routing system, a parser and TH code generation.
