homepage: http://haskell-distributed.github.com
changelog-type: ''
hash: fc0de146faca57d38e8dc93909679b7aa154bdf8e4e216346353ccd0234f96bb
test-bench-deps: {}
maintainer: Facundo Dominguez <facundo.dominguez@tweag.io>
synopsis: Compose network transports
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.3 && <5'
  network-transport: ! '>=0.4.0.0 && <0.5'
all-versions:
- '0.2.0.0'
- '0.2.0.1'
author: Edsko de Vries
latest: '0.2.0.1'
description-type: haddock
description: ''
license-name: BSD3
