homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 6116d386600ceb196f98122c662ae65836f285a6ea2d5d0491efaac3c628ecfe
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.8'
  text: ! '>=1.0'
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.14.0'
all-versions:
- '0.14.0'
author: ''
latest: '0.14.0'
description-type: haddock
description: ''
license-name: GPL-2
