homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 52506f10e52db32a3818441d90ab646f9d8da9862c917eed37523eed8c1c93aa
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.8'
  text: ! '>=1.0'
  data-default: -any
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.16.0'
all-versions:
- '0.14.0'
- '0.14.1'
- '0.15.0'
- '0.16.0'
author: ''
latest: '0.16.0'
description-type: haddock
description: ''
license-name: GPL-2
