homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 1db73965d06a880e21c3f1dd7cf56bf32eeaf7852f5d2763dd4b8722735e8572
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.8'
  text: ! '>=1.0'
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.14.1'
all-versions:
- '0.14.0'
- '0.14.1'
author: ''
latest: '0.14.1'
description-type: haddock
description: ''
license-name: GPL-2
