homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: cac25226b7afecb423b90bd5d5e86589c0b50c6bba2a0ae328bc67bec07944a2
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.8'
  text: ! '>=1.0'
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.15.0'
all-versions:
- '0.14.0'
- '0.14.1'
- '0.15.0'
author: ''
latest: '0.15.0'
description-type: haddock
description: ''
license-name: GPL-2
