changelog-type: ''
hash: c79d110944a71ab30f99076302f09093c26a48fca99f4b062bfeb86e5da57951
synopsis: Configuration types, parsers & renderers for AWS services
changelog: ''
all-versions:
- '0.1.0.0'
latest: '0.1.0.0'
description-type: haddock
description: Configuration types, parsers & renderers for AWS services, using configuration-tools.
