homepage: ''
changelog-type: ''
hash: 00c87c05138092e8dbcce528242d28ffa42408968f3d253b6e9d1ab8bb053cdf
test-bench-deps:
  MissingH: ! '>=1.0'
  base: ! '>4.8 && <5.0'
  parsec: -any
  HUnit: -any
  containers: -any
  mtl: -any
maintainer: David Farrell <shokku.ra@gmail.com>
synopsis: Fork of ConfigFile for Polar Game Engine
changelog: ''
basic-deps:
  MissingH: ! '>=1.0'
  base: ! '>4.8 && <5.0'
  parsec: -any
  containers: -any
  mtl: -any
all-versions:
- '0.1.0.0'
- '0.2.0.0'
- '0.2.0.1'
- '0.3.0.0'
author: John Goerzen (2004-2014), David Farrell
latest: '0.3.0.0'
description-type: haddock
description: A fork of ConfigFile updated and reworked to export a more consistent
  API for the Polar Game Engine.
license-name: BSD3
