changelog-type: ''
hash: 320f157df8f515d7a1fe18ca8016a4a3782bb1e53d943d3186e7484e52c1773b
test-bench-deps: {}
synopsis: Types for easy adding postgresql configuration to your program
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.7 && <4.8'
  time: -any
  monad-control: -any
  resource-pool: -any
  postgresql-simple: -any
  mtl: -any
  aeson: -any
all-versions:
- '0.0.1'
latest: '0.0.1'
description-type: markdown
description: ! "# What?\n\nSimple types and set of functions to quickly add configuration
  of\npostgresql to your Yesod site or whatever.\n\n# How?\n\nAdd separate file or
  section inside your existing config like that\n\n```yml\ndatabase:    \"dbname\"\nhost:
  \       \"127.0.0.1\"        # optional\nport:        \"5432\"             # optional\nuser:
  \       \"dbuser\"\npassword:    \"pass\"\npoolsize:    \"10\"               # optional
  maximum connections in pool\npooltimeout: \"60\"               # optional minimum
  connection lifetime\npoolstripes: \"1\"                # optional count of stripes
  in pool\n```\n\nand then in your program something like that\n\n```haskell\nconf
  <- decodeFile \"pgconfig.yml\"\n         >>= maybe (fail \"Could not parse pgconfig.yml\")
  return\npool <- createPGPool conf\npingPGPool pool\n```\n\nSo now you have a pool
  and can perform queries any way you like."
