changelog-type: ''
hash: 7cc03f768ed676f6345ee361550480bc4ee510624e10d9bd09653803d473d6cc
synopsis: Types for easy adding postgresql configuration to your program
changelog: ''
all-versions:
- '0.0.1'
latest: '0.0.1'
description-type: haddock
description: ''
