homepage: https://github.com/chpatrick/solga
changelog-type: ''
hash: e21313a9d9a9dd2661ad820f13d4eb3a56f07bba4603a695f7259a47cf0c2fc8
test-bench-deps: {}
maintainer: chpatrick@gmail.com
synopsis: Swagger generation for Solga
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4.8 && <5'
  unordered-containers: -any
  text: -any
  dlist: -any
  lens: -any
  mtl: -any
  swagger2: -any
  solga: -any
  http-types: -any
all-versions:
- '0.1.0.0'
author: Patrick Chilton
latest: '0.1.0.0'
description-type: haddock
description: Swagger generation for Solga
license-name: MIT
